### ISSUE TITLE
Image size limited

### ISSUE THREAD

**Issue by Nickname777777** [jonclayden/RNiftyReg#15]
I am not sure if this qualifies as a bug/issue, but it seems, as if the reg_tools limit image size to 2048.
This seems quite arbitrary to me, or are there reasons for this limit?
I am quite happy with the results I get, but now I have images to process that are larger than 2048px.
So I wonder if this limit could/should be changed.
Thanks

**Comment by jonclayden** [comment]
Hi. I think the limit is arbitrary, yes, but it comes from upstream NiftyReg code and [seems to still apply](https://github.com/KCL-BMEIS/niftyreg/blob/99d584e2b8ea0bffe7e65e40c8dc818751782d92/reg-lib/cpu/_reg_tools.cpp#L1111) in their most recent version. Since I didn't write that code, I don't know how much work would be needed to get it working for arbitrary image sizes, but from a quick glance at least some refactoring would be needed to avoid the use of statically-allocated arrays. I'd be willing to review a patch if you want to have a go at it, but it's unlikely I will get to it myself any time soon.

**Comment by Nickname777777** [comment]
Thank you very much for the explanation and the offering.
I would try to create a patch, but I have no working setups to debug C code.
So I think I will have to look for another solution.
Nevertheless, thanks again for your efforts and the RNiftyReg package!
Cheers
